### ISSUE TITLE
No content loaded after click Boot

### ISSUE THREAD

**Issue by ZedCheung** [sethm/ContrAltoJS#8]
I want to try ContrAltoJS on https://archives.loomcom.com/contraltojs/. I clicked **Boot** but saw nothing displayed in the **Screen**.
By the way, I like the project.

Device: Macbook Pro
Brower: Chrome & Safari

**Comment by sethm** [comment]
Thanks very much for pointing this out. I changed hostnames recently, and doing so broke disk loading.

It should be fixed now. You may need to Shift+Reload to clear your cache.

**Comment by sethm** [comment]
Closed because this issue has been fixed.
